spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
